import inquirer from 'inquirer';
import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import ora from 'ora';
import { execSync } from 'child_process';

export const init = async (options: { name?: string; db?: string }) => {
  const questions = [];

  if (!options.name) {
    questions.push({
      type: 'input',
      name: 'projectName',
      message: 'What is the name of your project?',
      default: 'my-allium-api',
    });
  }

  if (!options.db) {
    questions.push({
      type: 'list',
      name: 'database',
      message: 'Which database would you like to use?',
      choices: ['postgresql', 'mysql', 'mongodb', 'sqlite'],
    });
  }

  const answers = await inquirer.prompt(questions);

  const projectName = options.name || answers.projectName;
  const database = options.db || answers.database;
  const projectPath = path.join(process.cwd(), projectName);

  if (fs.existsSync(projectPath)) {
    console.log(chalk.red(`Directory ${projectName} already exists.`));
    return;
  }

  const spinner = ora('Scaffolding project...').start();

  try {
    // 1. Create directory
    fs.mkdirSync(projectPath);

    // 2. Create package.json
    const packageJson = {
      name: projectName,
      version: '1.0.0',
      scripts: {
        dev: 'ts-node-dev --respawn --transpile-only src/app.ts',
        build: 'tsc',
        start: 'node dist/app.js',
        'prisma:generate': 'prisma generate',
        'prisma:push': 'prisma db push',
      },
      dependencies: {
        fastify: '^4.24.3',
        '@prisma/client': '^5.5.2',
        'fastify-plugin': '^4.5.1',
        '@fastify/swagger': '^8.12.0',
        '@fastify/swagger-ui': '^1.10.1',
        mercurius: '^13.3.0', // GraphQL adapter for Fastify
        graphql: '^16.8.1',
        zod: '^3.22.4',
        'fastify-type-provider-zod': '^1.1.9',
      },
      devDependencies: {
        typescript: '^5.2.2',
        '@types/node': '^20.9.0',
        'ts-node': '^10.9.1',
        'ts-node-dev': '^2.0.0',
        prisma: '^5.5.2',
      },
    };

    fs.writeFileSync(
      path.join(projectPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // 3. Create tsconfig.json
    const tsConfig = {
      compilerOptions: {
        target: 'ES2020',
        module: 'commonjs',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules'],
    };

    fs.writeFileSync(
      path.join(projectPath, 'tsconfig.json'),
      JSON.stringify(tsConfig, null, 2)
    );

    // 4. Create src structure
    fs.mkdirSync(path.join(projectPath, 'src'));
    fs.mkdirSync(path.join(projectPath, 'src', 'plugins'));
    fs.mkdirSync(path.join(projectPath, 'src', 'modules'));

    // 5. Create app.ts
    const appTs = `import Fastify from 'fastify';
import { serializerCompiler, validatorCompiler } from 'fastify-type-provider-zod';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import mercurius from 'mercurius';

const app = Fastify({
  logger: true,
});

// Zod setup
app.setValidatorCompiler(validatorCompiler);
app.setSerializerCompiler(serializerCompiler);

// Swagger
app.register(swagger, {
  openapi: {
    info: {
      title: '${projectName} API',
      description: 'Generated by Allium',
      version: '1.0.0',
    },
  },
});

app.register(swaggerUi, {
  routePrefix: '/documentation',
});

// GraphQL
const schema = \`
  type Query {
    hello: String
  }
\`;

const resolvers = {
  Query: {
    hello: () => 'Hello from Allium!',
  },
};

app.register(mercurius, {
  schema,
  resolvers,
  graphiql: true,
});

// Health check
app.get('/health', async () => {
  return { status: 'ok' };
});

const start = async () => {
  try {
    await app.listen({ port: 3000 });
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};

start();
`;
    fs.writeFileSync(path.join(projectPath, 'src', 'app.ts'), appTs);

    // 6. Create Prisma schema
    fs.mkdirSync(path.join(projectPath, 'prisma'));
    const prismaSchema = `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${database}"
  url      = env("DATABASE_URL")
}
`;
    fs.writeFileSync(
      path.join(projectPath, 'prisma', 'schema.prisma'),
      prismaSchema
    );

    // 7. Create src/plugins/prisma.ts
    const prismaPlugin = `import fp from 'fastify-plugin';
import { PrismaClient } from '@prisma/client';

declare module 'fastify' {
  interface FastifyInstance {
    prisma: PrismaClient;
  }
}

export const prisma = new PrismaClient();

export default fp(async (fastify) => {
  fastify.decorate('prisma', prisma);

  fastify.addHook('onClose', async (fastify) => {
    await fastify.prisma.$disconnect();
  });
});
`;
    fs.writeFileSync(
      path.join(projectPath, 'src', 'plugins', 'prisma.ts'),
      prismaPlugin
    );

    // 8. Create .env
    const envContent = `DATABASE_URL="file:./dev.db"`; // Default for sqlite, others need change
    fs.writeFileSync(path.join(projectPath, '.env'), envContent);

    spinner.succeed(
      chalk.green(`Project ${projectName} created successfully!`)
    );
    console.log(chalk.yellow('\nNext steps:'));
    console.log(`  cd ${projectName}`);
    console.log('  npm install');
    console.log('  npm run dev');
  } catch (error) {
    spinner.fail(chalk.red('Failed to scaffold project.'));
    console.error(error);
  }
};
