import inquirer from 'inquirer';
import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import ora from 'ora';
import { execSync } from 'child_process';

export const init = async (options: {
  name?: string;
  db?: string;
  path?: string;
}) => {
  const questions = [];

  if (!options.name) {
    questions.push({
      type: 'input',
      name: 'projectName',
      message: 'What is the name of your project?',
      default: 'my-allium-api',
    });
  }

  if (!options.db) {
    questions.push({
      type: 'list',
      name: 'database',
      message: 'Which database would you like to use?',
      choices: ['postgresql', 'mysql', 'mongodb', 'sqlite'],
    });
  }

  const answers = await inquirer.prompt(questions);

  const projectName = options.name || answers.projectName;
  const database = options.db || answers.database;

  // Resolve path - note: in yarn workspaces, relative paths resolve from workspace root
  const basePath = options.path ? path.resolve(options.path) : process.cwd();
  const projectPath = path.join(basePath, projectName);

  // Helpful message if using relative path in workspace
  if (options.path && !path.isAbsolute(options.path)) {
    console.log(
      chalk.yellow(
        `Note: Relative paths resolve from workspace root when using yarn.`
      )
    );
    console.log(chalk.yellow(`Creating project in: ${projectPath}\n`));
  }

  if (fs.existsSync(projectPath)) {
    console.log(chalk.red(`Directory ${projectName} already exists.`));
    return;
  }

  const spinner = ora('Scaffolding project...').start();

  try {
    // 1. Create directory
    fs.mkdirSync(projectPath, { recursive: true });

    // 2. Create package.json
    const packageJson: any = {
      name: projectName,
      version: '1.0.0',
      scripts: {
        dev: 'ts-node-dev --respawn --transpile-only src/app.ts',
        build: 'tsc',
        start: 'node dist/app.js',
        'prisma:generate': 'prisma generate',
        'prisma:push': 'prisma db push',
      },
      dependencies: {
        fastify: '^4.24.3',
        '@prisma/client': '^5.5.2', // Should be updated to 6/7 compatible if available, keeping existing version for now or assuming user handles upgrade
        'fastify-plugin': '^4.5.1',
        '@fastify/swagger': '^8.12.0',
        '@fastify/swagger-ui': '^1.10.1',
        mercurius: '^13.3.0',
        graphql: '^16.8.1',
        zod: '^3.22.4',
        'fastify-type-provider-zod': '^1.1.9',
        dotenv: '^16.3.1',
      },
      devDependencies: {
        typescript: '^5.2.2',
        '@types/node': '^20.9.0',
        'ts-node': '^10.9.1',
        'ts-node-dev': '^2.0.0',
        prisma: '^5.5.2',
      },
    };

    if (database === 'sqlite') {
      packageJson.dependencies['@prisma/adapter-better-sqlite3'] = '^7.0.0';
      packageJson.dependencies['better-sqlite3'] = '^11.0.0';
      packageJson.devDependencies['@types/better-sqlite3'] = '^7.6.0';
    } else if (database === 'postgresql') {
      packageJson.dependencies['@prisma/adapter-pg'] = '^7.0.0';
      packageJson.dependencies['pg'] = '^8.11.0';
      packageJson.devDependencies['@types/pg'] = '^8.10.0';
    }

    fs.writeFileSync(
      path.join(projectPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // 3. Create tsconfig.json
    const tsConfig = {
      compilerOptions: {
        target: 'ES2020',
        module: 'commonjs',
        outDir: './dist',
        rootDir: '.',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
      },
      include: ['src/**/*', '.allium/**/*'],
      exclude: ['node_modules', 'dist', '.allium/models'],
    };

    fs.writeFileSync(
      path.join(projectPath, 'tsconfig.json'),
      JSON.stringify(tsConfig, null, 2)
    );

    // 4. Create src structure
    fs.mkdirSync(path.join(projectPath, 'src'));
    fs.mkdirSync(path.join(projectPath, 'src', 'plugins'));
    fs.mkdirSync(path.join(projectPath, 'src', 'modules'));

    // 5. Create app.ts
    const appTs = `import Fastify from 'fastify';
import { serializerCompiler, validatorCompiler } from 'fastify-type-provider-zod';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import mercurius from 'mercurius';

const app = Fastify({
  logger: true,
});

// Zod setup
app.setValidatorCompiler(validatorCompiler);
app.setSerializerCompiler(serializerCompiler);

// Swagger
app.register(swagger, {
  openapi: {
    info: {
      title: '${projectName} API',
      description: 'Generated by Allium',
      version: '1.0.0',
    },
  },
});

app.register(swaggerUi, {
  routePrefix: '/documentation',
});

// GraphQL
const schema = \`
  type Query {
    hello: String
  }
\`;

const resolvers = {
  Query: {
    hello: () => 'Hello from Allium!',
  },
};

app.register(mercurius, {
  schema,
  resolvers,
  graphiql: true,
});

// Health check
app.get('/health', async () => {
  return { status: 'ok' };
});

const start = async () => {
  try {
    await app.listen({ port: 3000 });
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};

start();
`;
    fs.writeFileSync(path.join(projectPath, 'src', 'app.ts'), appTs);

    // 6. Create Prisma schema
    fs.mkdirSync(path.join(projectPath, 'prisma'));
    const prismaSchema = `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${database}"
}
`;
    fs.writeFileSync(
      path.join(projectPath, 'prisma', 'schema.prisma'),
      prismaSchema
    );

    // 7. Create prisma.config.ts
    const prismaConfig = `import 'dotenv/config';
import { defineConfig } from '@prisma/config';

export default defineConfig({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});
`;
    fs.writeFileSync(path.join(projectPath, 'prisma.config.ts'), prismaConfig);

    // 8. Create src/plugins/prisma.ts
    let prismaPlugin = `import fp from 'fastify-plugin';
import { PrismaClient } from '@prisma/client';
import 'dotenv/config';
`;

    if (database === 'sqlite') {
      prismaPlugin += `import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';
import Database from 'better-sqlite3';

const connection = new Database(process.env.DATABASE_URL!.replace('file:', ''));
const adapter = new PrismaBetterSqlite3(connection);
const prisma = new PrismaClient({ adapter });
`;
    } else if (database === 'postgresql') {
      prismaPlugin += `import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const connection = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(connection);
const prisma = new PrismaClient({ adapter });
`;
    } else if (database === 'mongodb') {
      prismaPlugin += `
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});
`;
    } else {
      // Fallback for others
      prismaPlugin += `
const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
});
`;
    }

    prismaPlugin += `
declare module 'fastify' {
  interface FastifyInstance {
    prisma: PrismaClient;
  }
}

export { prisma };

export default fp(async (fastify) => {
  fastify.decorate('prisma', prisma);

  fastify.addHook('onClose', async (fastify) => {
    await fastify.prisma.$disconnect();
  });
});
`;
    fs.writeFileSync(
      path.join(projectPath, 'src', 'plugins', 'prisma.ts'),
      prismaPlugin
    );

    // 8. Create .env
    let envContent = '';

    switch (database) {
      case 'postgresql':
        envContent = `DATABASE_URL="postgresql://user:password@localhost:5432/${projectName}?schema=public"`;
        break;
      case 'mysql':
        envContent = `DATABASE_URL="mysql://user:password@localhost:3306/${projectName}"`;
        break;
      case 'mongodb':
        envContent = `DATABASE_URL="mongodb://localhost:27017/${projectName}"`;
        break;
      case 'sqlite':
      default:
        envContent = `DATABASE_URL="file:./dev.db"`;
        break;
    }

    fs.writeFileSync(path.join(projectPath, '.env'), envContent);

    spinner.succeed(
      chalk.green(`Project ${projectName} created successfully!`)
    );
    console.log(chalk.yellow('\nNext steps:'));
    console.log(`  cd ${projectName}`);
    console.log('  npm install');
    console.log('  npm run dev');
  } catch (error) {
    spinner.fail(chalk.red('Failed to scaffold project.'));
    console.error(error);
  }
};
